name: Compilar ejecutable para Windows

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl selenium

    - name: Crear ejecutable .EXE
      run: |
        python -m PyInstaller --onefile --noconsole script_tandil.py

    - name: Guardar ejecutable como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: Ejecutable-Tandil-Windows
        path: dist/script_tandil.exe
